### ISSUE TITLE
Installation and GSHHS path

### ISSUE THREAD

**Issue by danielchaco** [aragong/coastline-loader#1]
Good job and thank you!

They way I could install the environment was with the line `conda env create -f environment.yml`. I had some issues finding the GSHHG_SHP_DATABASE_PATH path, so I suggest either explain more how to assure the package will appear in the environ paths or let introduce the path in the method. I had to change it manually and worked, so thank you very much!

Regards,

Daniel

**Comment by aragong** [comment]
Hi @danielchaco, thank you for the suggestion!

I've just added an extra example of how to set this variable in the README, hope it helps to clarify (see image attached.)

![image](https://user-images.githubusercontent.com/48764870/157610109-39bacbb3-ceec-41f6-8e5d-f0e4ad425354.png)
